// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.4
// source: sample/sample.proto

package categorizationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Categorization_CategorizationArticle_FullMethodName = "/categorization.Categorization/CategorizationArticle"
)

// CategorizationClient is the client API for Categorization service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategorizationClient interface {
	CategorizationArticle(ctx context.Context, in *CategorizationArticleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type categorizationClient struct {
	cc grpc.ClientConnInterface
}

func NewCategorizationClient(cc grpc.ClientConnInterface) CategorizationClient {
	return &categorizationClient{cc}
}

func (c *categorizationClient) CategorizationArticle(ctx context.Context, in *CategorizationArticleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Categorization_CategorizationArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategorizationServer is the server API for Categorization service.
// All implementations must embed UnimplementedCategorizationServer
// for forward compatibility.
type CategorizationServer interface {
	CategorizationArticle(context.Context, *CategorizationArticleRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedCategorizationServer()
}

// UnimplementedCategorizationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCategorizationServer struct{}

func (UnimplementedCategorizationServer) CategorizationArticle(context.Context, *CategorizationArticleRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CategorizationArticle not implemented")
}
func (UnimplementedCategorizationServer) mustEmbedUnimplementedCategorizationServer() {}
func (UnimplementedCategorizationServer) testEmbeddedByValue()                        {}

// UnsafeCategorizationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategorizationServer will
// result in compilation errors.
type UnsafeCategorizationServer interface {
	mustEmbedUnimplementedCategorizationServer()
}

func RegisterCategorizationServer(s grpc.ServiceRegistrar, srv CategorizationServer) {
	// If the following call pancis, it indicates UnimplementedCategorizationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Categorization_ServiceDesc, srv)
}

func _Categorization_CategorizationArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategorizationArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategorizationServer).CategorizationArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Categorization_CategorizationArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategorizationServer).CategorizationArticle(ctx, req.(*CategorizationArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Categorization_ServiceDesc is the grpc.ServiceDesc for Categorization service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Categorization_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "categorization.Categorization",
	HandlerType: (*CategorizationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CategorizationArticle",
			Handler:    _Categorization_CategorizationArticle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sample/sample.proto",
}
